name: benchmark

on:
  push: {}
  pull_request: {}

jobs:
  job:
    name: Run-benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Run benchmark
        run: |
          cmake --preset=benchmark
          cmake --build --preset=benchmark
          ./build/benchmark/benchmarks/smol_bench
