name: clang-tidy

on:
  push: {}
  pull_request: {}

jobs:
  job:
    name: run-clang-tidy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Configure CMake
      run: cmake --preset=linux

    - name: Run linter checks
      run: clang-tidy -p build/linux --format-style='file' ./*.h unit_test/*.cpp
