name: Unit Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Configure CMake
      run: cmake --preset=linux
    - name: Run linter checks
      run: bash ./scripts/run_linter_checks.sh
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build
      run: cmake --workflow --preset=linux
    - name: Test
      run: ./build/linux/unit_test/unit_test
