name: Unit Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Configure CMake
      run: cmake --preset=linux
    - name: Run linter checks
      run: bash ./scripts/run_linter_checks.sh
  build:
    name: Build, Test, Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Build and Test
        run: |
          cmake --workflow --preset=linux
          ./build/linux/unit_test/unit_test
      - name: Generate code coverage report
        run: |
          sudo apt-get install -y llvm
          ./scripts/generate_coverage_report.sh
